//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popova_09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public int MonkeyId { get; set; }
        public System.DateTime dateSale { get; set; }
        public decimal StartPrice { get; set; }
        public decimal LastPrice { get; set; }
        public string answer { get; set; }
        public string surname { get; set; }
    
        public virtual Monkey Monkey { get; set; }
    }
}
